[workspace]
members = [
    "unreal-api",
    "unreal-ffi",
    "unreal-reflect",
    "unreal-api-derive",
    "unreal-rust-example",
    "gameplay-plugins/unreal-movement",
]
#[profile.release]
#debug = true
